import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import { SearchIcon, MicrophoneIcon } from '@heroicons/react/solid'
import Footer from '../components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/dist/client/router'

export default function Home() {
  const searchInputRef = useRef(null);
  const router = useRouter();

  const search = (e) => {
    e.preventDefault();
    const searchText = searchInputRef.current.value;
    if (!searchText) return;
    router.push(`/search?query=${searchText}`);
  };

  return (
    <div className="h-screen flex flex-col">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      {/* Body */}
      <form className="flex flex-col items-center mt-44 flex-grow">
        <Image
          src="https://www.google.co.in/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          width={300}
          height={100}
        />
        <div 
          className="flex border border-gray-200 w-full max-w-md mt-5 sm:max-w-xl p-2 rounded-full hover:shadow-lg focus-within:shadow-lg px-5 py-3 items-center"
        >
          <SearchIcon className="h-5 mr-2 text-gray-500" />
          <input ref={searchInputRef} type="text" className="flex-grow focus:outline-none" />
          <MicrophoneIcon className="h-5" />
        </div>
        {/* Buttons */}
        <div className="flex justify-center mt-8 flex-col w-1/2 space-y-2 sm:flex-row sm:space-y-0 sm:space-x-3">
          <button className="btn" onClick={search}>Google Search</button>
          <button className="btn" onClick={search}>I'm Feeling Lucky</button>
        </div>
      </form>
      
      {/* Footer */}
      <Footer />
    </div>
  )
}
